### ISSUE TITLE
No module named 'vacuum_map_parser_ijai'

### ISSUE THREAD

**Issue by xrays72** [Tarh-76/HA-custom-components-Xiaomi-Cloud-Map-Extractor-Ijai-Support#1]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi.
Error on check configuration:
Platform error 'camera' from integration 'xiaomi_cloud_map_extractor' - No module named 'vacuum_map_parser_ijai'

### What version of an integration has described problem?

ijai_map_image

### What vacuum model do you have problems with?

ijai.vacuum.v1

### What version of Home Assistant do you use?

2024.5.1

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: vacuum_extractor_camera
    host: !secret xiaomi_mop_ip
    token: !secret xiaomi_mop_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: "cn"
    draw: ['all']
    force_api: ijai
```
